### ISSUE TITLE
Code Runner VSCode plugin gets added to profile

### ISSUE THREAD

**Issue by bykiandra** [mastorm/CodeStats.Client#5]
I use the [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) VSCode plugin to run some of my programs.

Anything printed in the output panel by the plugin is added to my Code::Stats profile as __code-runner-output__. You can see it on my profile [here](https://codestats.net/users/Saoskia).

**Comment by SirTobyB** [comment]
Hi Saoskia,
you're mentioning a VS Code plugin, so maybe you mean the [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=riussi.code-stats-vscode)?

If so, you should create the issue [here](https://gitlab.com/juha.ristolainen/code-stats-vscode/issues), because this is the repo of the Visual Studio extension.

**Comment by bykiandra** [comment]
Oops, my mistake. Thanks for the reply.
